// <auto-generated />
using System;
using Analysis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Analysis.Infrastructure.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20250823160302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Analysis.Domain.Entities.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AxeInapplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("axe_inapplicable");

                    b.Property<int?>("AxeIncomplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("axe_incomplete");

                    b.Property<int?>("AxeNeedsReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("axe_needs_review");

                    b.Property<int?>("AxePasses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("axe_passes");

                    b.Property<int?>("AxeRecommendations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("axe_recommendations");

                    b.Property<int?>("AxeViolations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("axe_violations");

                    b.Property<string>("ContentInput")
                        .HasColumnType("longtext")
                        .HasColumnName("content_input");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateAnalysis")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_analysis");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("EaInapplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ea_inapplicable");

                    b.Property<int?>("EaIncomplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ea_incomplete");

                    b.Property<int?>("EaNeedsReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ea_needs_review");

                    b.Property<int?>("EaPasses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ea_passes");

                    b.Property<int?>("EaRecommendations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ea_recommendations");

                    b.Property<int?>("EaViolations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ea_violations");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("result_json");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("status");

                    b.Property<string>("SummaryResult")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("summary_result");

                    b.Property<string>("ToolUsed")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("tool_used");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("WcagLevel")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("wcag_level");

                    b.Property<string>("WcagVersion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("wcag_version");

                    b.HasKey("Id");

                    b.HasIndex("DateAnalysis")
                        .HasDatabaseName("idx_analysis_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_analysis_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_analysis_user");

                    b.ToTable("ANALYSIS", (string)null);
                });

            modelBuilder.Entity("Analysis.Domain.Entities.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("error_code");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<int>("ResultId")
                        .HasColumnType("int")
                        .HasColumnName("result_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("WcagCriterionId")
                        .HasColumnType("int")
                        .HasColumnName("wcag_criterion_id");

                    b.HasKey("Id");

                    b.HasIndex("ResultId")
                        .HasDatabaseName("idx_errors_result");

                    b.ToTable("ERRORS", (string)null);
                });

            modelBuilder.Entity("Analysis.Domain.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("level");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("WcagCriterion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("wcag_criterion");

                    b.Property<int>("WcagCriterionId")
                        .HasColumnType("int")
                        .HasColumnName("wcag_criterion_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("idx_results_analysis");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_results_severity");

                    b.ToTable("RESULTS", (string)null);
                });

            modelBuilder.Entity("Analysis.Domain.Entities.Error", b =>
                {
                    b.HasOne("Analysis.Domain.Entities.Result", "Result")
                        .WithMany("Errors")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Analysis.Domain.Entities.Result", b =>
                {
                    b.HasOne("Analysis.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Results")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Analysis.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Analysis.Domain.Entities.Result", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
