namespace Analysis.Application.Dtos;

public record AnalysisDto(
    int Id,
    int UserId,
    DateTime DateAnalysis,
    string ContentType,
    string? ContentInput,
    string? SourceUrl,
    string ToolUsed,
    string Status,
    string SummaryResult,
    string ResultJson,
    int? DurationMs,
    string WcagVersion,
    string WcagLevel,
    int? AxeViolations,
    int? AxeNeedsReview,
    int? AxeRecommendations,
    int? AxePasses,
    int? AxeIncomplete,
    int? AxeInapplicable,
    int? EaViolations,
    int? EaNeedsReview,
    int? EaRecommendations,
    int? EaPasses,
    int? EaIncomplete,
    int? EaInapplicable,
    DateTime CreatedAt,
    DateTime UpdatedAt
);

public record AnalysisCreateDto(
    int UserId,
    DateTime DateAnalysis,
    string ContentType,
    string ContentInput,
    string SourceUrl,
    string ToolUsed,
    string Status,
    string SummaryResult,
    string ResultJson,
    int? DurationMs,
    string WcagVersion,
    string WcagLevel,
    int? AxeViolations,
    int? AxeNeedsReview,
    int? AxeRecommendations,
    int? AxePasses,
    int? AxeIncomplete,
    int? AxeInapplicable,
    int? EaViolations,
    int? EaNeedsReview,
    int? EaRecommendations,
    int? EaPasses,
    int? EaIncomplete,
    int? EaInapplicable
);

public record AnalysisPatchDto(
    string? ContentType,
    string? ContentInput,
    string? SourceUrl,
    string? ToolUsed,
    string? Status,
    string? SummaryResult,
    string? ResultJson,
    int? DurationMs,
    string? WcagVersion,
    string? WcagLevel,
    int? AxeViolations,
    int? AxeNeedsReview,
    int? AxeRecommendations,
    int? AxePasses,
    int? AxeIncomplete,
    int? AxeInapplicable,
    int? EaViolations,
    int? EaNeedsReview,
    int? EaRecommendations,
    int? EaPasses,
    int? EaIncomplete,
    int? EaInapplicable
);